version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-material mkdocs-navsorted-plugin mkdocs-apidescribed-plugin git+https://github.com/idlesign/django-sitetree

mkdocs:
  configuration: mkdocs.yml

