[project]
name = "django-sitetree"
dynamic = ["version"]
description = "This reusable Django app introduces site tree, menu and breadcrumbs navigation elements."
authors = [
    { name = "Igor Starikov", email = "idlesign@yandex.ru" }
]
readme = "README.md"

classifiers = [
    "Development Status :: 5 - Production/Stable", #   3 - Alpha; 5 - Production/Stable
    "Framework :: Django",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: BSD License"
]

license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.10"
keywords = ["navigation", "django"]
dependencies = []

[project.urls]
Homepage = "https://github.com/idlesign/django-sitetree"
Documentation = "https://django-sitetree.readthedocs.io/"

[dependency-groups]
dev = [
    {include-group = "docs"},
    {include-group = "linters"},
    {include-group = "tests"},
]
docs = [
    "mkdocs-material",
    "mkdocs-apidescribed-plugin",
    "mkdocs-navsorted-plugin",
]
linters = [
    "ruff",
]
tests = [
    "pytest",
    "pytest-djangoapp>=1.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/sitetree/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/sitetree"]

[tool.hatch.build.targets.sdist]
packages = ["src/"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--pyargs"

[tool.coverage.run]
source = [
    "src/",
]
omit = [
    "src/sitetree/migrations/*"
]

[tool.coverage.report]
fail_under = 96.00
exclude_also = [
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
]
