# Generated by Django 5.2.2 on 2025-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitetree", "0002_alter_treeitem_parent_alter_treeitem_tree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tree",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Site tree title for presentational purposes.",
                max_length=256,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="treeitem",
            name="title",
            field=models.CharField(
                help_text="Site tree item title. Can contain template variables E.g.: {{ mytitle }}.",
                max_length=256,
                verbose_name="Title",
            ),
        ),
    ]
