# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, verbose_name='Created')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('contents', models.TextField(verbose_name='Contents')),
            ],
        ),
    ]
